services:
#    bfa_geo_location.example:
#        class: Bfa\GeoLocationBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    bfa.sonata.leafletmap:
      class: Bfa\GeoLocationBundle\Form\Type\LeafletMap
      tags:
        - {name: form.type, label: leafletmap, alias: leafletmap }

